-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 10:35:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assinatura` (
  `idAssinatura` INT NOT NULL,
  `Nome` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idAssinatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assinante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assinante` (
  `email` VARCHAR(80) NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `endereço` VARCHAR(200) NOT NULL,
  `nascimento` DATE NOT NULL,
  `Assinatura` INT NOT NULL,
  `senha` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_Assinante_Assinatura_idx` (`Assinatura` ASC) VISIBLE,
  CONSTRAINT `fk_Assinante_Assinatura`
    FOREIGN KEY (`Assinatura`)
    REFERENCES `mydb`.`Assinatura` (`idAssinatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja` (
  `Email` VARCHAR(60) NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Site` VARCHAR(80) NOT NULL,
  `Senha` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Tipo` VARCHAR(60) NOT NULL,
  `Cor` VARCHAR(60) NOT NULL,
  `Ingrediente_Principal` VARCHAR(60) NOT NULL,
  `Preço` DOUBLE NOT NULL,
  `Avaliação` INT NOT NULL,
  `Estoque` INT NULL,
  `Loja` INT NOT NULL,
  `Marca` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idProduto`, `Loja`),
  INDEX `fk_Produto_Loja1_idx` (`Loja` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Loja1`
    FOREIGN KEY (`Loja`)
    REFERENCES `mydb`.`Loja` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrinho` (
  `Produto_idProduto` INT NOT NULL,
  `Produto_Loja` INT NOT NULL,
  `Assinante` VARCHAR(80) NOT NULL,
  `Quantidade` INT NOT NULL,
  `Pagamento` TINYINT(1) NOT NULL,
  `Total` DOUBLE NULL,
  INDEX `fk_Carrinho_Produto1_idx` (`Produto_idProduto` ASC, `Produto_Loja` ASC) VISIBLE,
  PRIMARY KEY (`Produto_idProduto`, `Produto_Loja`, `Assinante`),
  INDEX `fk_Carrinho_Assinante1_idx` (`Assinante` ASC) VISIBLE,
  CONSTRAINT `fk_Carrinho_Produto1`
    FOREIGN KEY (`Produto_idProduto` , `Produto_Loja`)
    REFERENCES `mydb`.`Produto` (`idProduto` , `Loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrinho_Assinante1`
    FOREIGN KEY (`Assinante`)
    REFERENCES `mydb`.`Assinante` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cupom` (
  `Serial` VARCHAR(12) NOT NULL,
  `Desconto` DOUBLE NOT NULL,
  `Assinatura_idAssinatura` INT NOT NULL,
  PRIMARY KEY (`Serial`),
  INDEX `fk_Cupom_Assinatura1_idx` (`Assinatura_idAssinatura` ASC) VISIBLE,
  CONSTRAINT `fk_Cupom_Assinatura1`
    FOREIGN KEY (`Assinatura_idAssinatura`)
    REFERENCES `mydb`.`Assinatura` (`idAssinatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LojaCupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LojaCupom` (
  `Quantidade` INT NULL,
  `Validade` DATE NOT NULL,
  `Cupom` VARCHAR(12) NOT NULL,
  `Loja` VARCHAR(60) NOT NULL,
  INDEX `fk_LojaCupom_Cupom1_idx` (`Cupom` ASC) VISIBLE,
  INDEX `fk_LojaCupom_Loja1_idx` (`Loja` ASC) VISIBLE,
  PRIMARY KEY (`Loja`, `Cupom`),
  CONSTRAINT `fk_LojaCupom_Cupom1`
    FOREIGN KEY (`Cupom`)
    REFERENCES `mydb`.`Cupom` (`Serial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LojaCupom_Loja1`
    FOREIGN KEY (`Loja`)
    REFERENCES `mydb`.`Loja` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
